#! /bin/sh

# clear all window rules
bspc rule -r "*"

# start up programs
/usr/bin/dunst &
polybar &

# apply key mappings
setxkbmap -option caps:super

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# couple settings I like
bspc config single_monocle true

# set some colours
bspc config border_width 1
bspc config normal_border_color '#0C1115'
bspc config focused_border_color '#33ccff'
